apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-search-api
  labels:
    app: location-search-api
    tier: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-search-api
  template:
    metadata:
      labels:
        app: location-search-api
        tier: webserver
    spec:
      containers:
        - name: location-search-api
          image: alahkaih/location-search-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
          env:
            - name: SERVER_PORT
              value: "7000"
          livenessProbe:
            tcpSocket:
              port: 7000
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 7000
            initialDelaySeconds: 15
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: SearchAPIServer
spec:
  ports:
    - port: 90
      targetPort: 7000
  selector:
    app: location-search-api
  type: LoadBalancer